---
name: Run Full Integration Test
env:
  TMPDIR: /tmp/
  SNAKEMAKE_PROFILE: /__w/vdblab-shotgun/vdblab-shotgun/.test/profile/

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: snakemake/snakemake:v7.31.1
      options: --privileged  --workdir /github/workspace --rm -e TMPDIR
      volumes:
        - /github/workspace/:/github/workspace/
    name: Test Pipelines
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test shotgun up to dedup
        run: bash ./test.sh preprocess-gha sim || (cat tmppre_sim/logs/* && exit 1)
          # echo `pwd` && snakemake
          # --directory tmpsim_pre/
          # --snakefile workflow/Snakefile
          # --cores 1
          # --jobs 1
          # --resources mem_mb=5000
          # --use-singularity
          # --singularity-prefix /github/workspace/.singularity/
          # --singularity-args '-B /github/'
          # --config
          # sample=test
          # R1=["$PWD/.test/simulated/1_depth100000_R1.fastq.gz"]
          # R2=["$PWD/.test/simulated/1_depth100000_R2.fastq.gz"]
          # dedup_platform=SRA
          # stage=preprocess
          # --force dedup/473_R1.fastq.gz reports/473_hostdepletion.stats

      - name: Test with pytest
        run: |
          pip install pytest
          pytest
